/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minorp;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author gaurav
 */
public class AddEmp extends javax.swing.JFrame {

    /**
     * Creates new form AddEmp
     */
    public AddEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        eag = new javax.swing.JTextField();
        edoj = new javax.swing.JTextField();
        addemp = new javax.swing.JButton();
        epass = new javax.swing.JPasswordField();
        repass = new javax.swing.JPasswordField();
        ebck = new javax.swing.JButton();
        lgot = new javax.swing.JButton();
        lbeid = new javax.swing.JLabel();
        lbag = new javax.swing.JLabel();
        lbdoj = new javax.swing.JLabel();
        lbrpass = new javax.swing.JLabel();
        lbenam = new javax.swing.JLabel();
        lbpas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Employee Id");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Date Of Joining");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("Re-Enter Password");

        eid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        eid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eidFocusLost(evt);
            }
        });

        ename.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enameFocusLost(evt);
            }
        });

        eag.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        eag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eagFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eagFocusLost(evt);
            }
        });

        edoj.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        edoj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edojFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edojFocusLost(evt);
            }
        });

        addemp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addemp.setText("Add");
        addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempActionPerformed(evt);
            }
        });

        epass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                epassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                epassFocusLost(evt);
            }
        });

        repass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                repassFocusLost(evt);
            }
        });

        ebck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ebck.setText("Back");
        ebck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebckActionPerformed(evt);
            }
        });

        lgot.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lgot.setText("Logout");
        lgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgotActionPerformed(evt);
            }
        });

        lbeid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbeid.setForeground(new java.awt.Color(51, 255, 255));

        lbag.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbag.setForeground(new java.awt.Color(51, 255, 255));

        lbdoj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbdoj.setForeground(new java.awt.Color(51, 255, 255));

        lbrpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbrpass.setForeground(new java.awt.Color(51, 255, 255));

        lbenam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbenam.setForeground(new java.awt.Color(51, 255, 255));

        lbpas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbpas.setForeground(new java.awt.Color(51, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("ADD EMPLOYEE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(134, 134, 134)
                .addComponent(lgot))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ebck)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(addemp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addComponent(repass))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(108, 108, 108)
                                .addComponent(epass))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(edoj))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(151, 151, 151)
                                .addComponent(eag))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)
                                .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(136, 136, 136)
                                .addComponent(ename)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbpas)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbeid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbdoj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbenam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbrpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lgot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbeid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbenam))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(eag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdoj, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(edoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(epass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbpas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbrpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(repass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(ebck))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int ae;
class validateemp
{
    private void valdeid()
    {
        String a;
        int n;
        n=Integer.parseInt(eid.getText());
        a = eid.getText();
        String pattern = "(\\d{4})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((1000<n) && (n<=1999)))
            {
                lbeid.setText("Invalid");
                ae++;
            }
        } 
        else 
        {
            lbeid.setText("Invalid");
            ae++;
        }
    }
    private void valdename()
    {
        String a;
        int n;
        n=ename.getText().length();
        a = ename.getText();
        String pattern = "[a-zA-Z\\s]*";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((2<n) && (n<40)))
            {
                lbenam.setText("Invalid");
                ae++;
            }
        } 
        else 
        {
            lbenam.setText("Invalid");
            ae++;
        }
    }
    private void valdpassword()
    {
         String a;
        a = epass.getText();
        String pattern = "(\\S{3,})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( ))
        {
          
        }
        else
        {
            lbpas.setText("Invalid");
            ae++;
        }
    }
    private void valddate() 
    {
        int f=1,g=1,yr;
        String a,year,month,day;
        a =edoj.getText();
        if(a.charAt(4)=='-' && a.charAt(7)=='-')
        {
            year=a.substring(0,4);
            month=a.substring(5,7);
            day=a.substring(8);
            yr=Integer.parseInt(year);
        
       /* else
        {
            f=0;
        } */
            if (month.equals("04")||month.equals("06")||month.equals("07")||month.equals("09")||
              month.equals("11"))
            {
                g=1;
                String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                Pattern r1 = Pattern.compile(patternd);
                Matcher m1 = r1.matcher(day);
                if (m1.matches( )||day.equals("30"))
                {
                    g=1;
                }
                 else
                {
                    f=0;
                }
          // 30 days
            }
            else if (month.equals("01")||month.equals("03")||month.equals("05")||month.equals("07")
              ||month.equals("08")||month.equals("10")||month.equals("12"))
            {
                g=1;
                String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                Pattern r1 = Pattern.compile(patternd);
                Matcher m1 = r1.matcher(day);
                if (m1.matches( )||day.equals("30")||day.equals("31"))
                {
                    g=1;
                }
                else
                {
                    f=0;
                }
          //31 days
            }
            else if (month.equals("02"))
            {
                g=1;
                int c;
                c=Integer.parseInt(year);
                if ((c%4==0 && c%100==0)||(c%400)==0)
                {
                    String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                    Pattern r1 = Pattern.compile(patternd);
                    Matcher m1 = r1.matcher(day);
                    if (m1.matches( ))
                    {
                        g=1;
                    }
                    else
                    {
                        f=0;
                    }
                }
                else
                {
                    String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8))$";
                    Pattern r1 = Pattern.compile(patternd);
                    Matcher m1 = r1.matcher(day);
                    if (m1.matches( )||day.equals("09")||day.equals("19"))
                    {
                  //  JOptionPane.showMessageDialog(null,"Valid Day");
                    }
                    else
                    {
                        f=0;
                    }
                }
            }
            else
            {
                f=0;
            }
            String patterny = "^((20)\\d{2})$";
            Pattern r = Pattern.compile(patterny);
            Matcher m = r.matcher(year);
            if (m.matches( ))
            {
                if(!(yr<=2020))
                {
                    f=0;
                }
                else
                    g=1;
            }
            else
            {
                f=0;
            }
            if (f==0)
            {
                lbdoj.setText("Invalid");
                ae++;
            }
            if (g==1 && f!=0)
            {
           // JOptionPane.showMessageDialog(null,"Valid date");
            }
        }
        else
        {
            lbdoj.setText("Invalid");
            ae++;        
        }
    }
    private void valdage()
    {
        String a;
        int n;
        n=Integer.parseInt(eag.getText());
        a = eag.getText();
        String pattern = "(\\d{2})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((18<n) && (n<60)))
            {
                lbag.setText("Invalid");
                ae++;
            }
        } 
        else 
        {
            lbag.setText("Invalid");
            ae++;
        }
    }
    private void passmatch()
    {
        String p,pr;
        p=epass.getText();
        pr=repass.getText();
        if(!(p.equals(pr)))
        {
            lbrpass.setText("Password do not match");
            ae++;
        }
    }
}
class addemp
{
    void emp()
    {
        int ed,eage;
        String enam,dojn,pass,rpass,qry;
        ed=Integer.parseInt(eid.getText());
        eage=Integer.parseInt(eag.getText());
        enam=ename.getText();
        dojn=edoj.getText();
        pass=epass.getText();
        rpass=repass.getText();
        try
        {
            Connection cn;
            Statement st;
            int rs;
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab","root","GAUsing@2011");
            st=cn.createStatement();
            qry="insert into employee(eid,ename,eage,Doj,pass) values("+ed+",'"+enam+"',"+eage+",'"+dojn+"','"+pass+"')";
            rs=st.executeUpdate(qry);
            if(rs>0)
            {
                JOptionPane.showMessageDialog(null,"New Employee Added");
            }
            cn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error : "+ex);
        }
    }
    void adlgn()
    {
        int ed;
        String pss,qr;
        ed=Integer.parseInt(eid.getText());
        pss=epass.getText();
        try
        {
            Connection cn;
            Statement st;
            int rs;
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab","root","GAUsing@2011");
            st=cn.createStatement();
            qr="insert into login(userid,pass,type) values("+ed+",'"+pss+"',"+0+")";
            rs=st.executeUpdate(qr);
            if(rs>0)
            {
                
            }
            cn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error : "+ex);
        }
    }
    void eclear()
    {
        eid.setText("");
        ename.setText("");
        edoj.setText("");
        eag.setText("");
        epass.setText("");
        repass.setText("");
    }
}
    private void addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempActionPerformed
        addemp adem=new addemp();
        int dialogbt=JOptionPane.YES_NO_OPTION;
                dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to confirm ?","Confirmation",dialogbt);
                if(dialogbt==JOptionPane.YES_NO_OPTION)
                {
                    if(ae!=0)
                        {
                            JOptionPane.showMessageDialog(null,"One or more fields are invalid");
                        }
                        else
                        {
                            adem.emp();
                            adem.adlgn();
                            adem.eclear();
                        }
                    this.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Employee Not Added");
                    this.setVisible(true);
                    adem.eclear();
                }
    }//GEN-LAST:event_addempActionPerformed

    private void ebckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebckActionPerformed
        EmpMan em=new EmpMan();
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ebckActionPerformed

    private void lgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgotActionPerformed
        Login lg=new Login();
        int dialogbt=JOptionPane.YES_NO_OPTION;
        dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Confirmation",dialogbt);
        if(dialogbt==JOptionPane.YES_NO_OPTION)
        {
            lg.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.setVisible(true);
        }
    }//GEN-LAST:event_lgotActionPerformed

    private void eagFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eagFocusLost
        if(eag.getText().length()==0)
        {
            lbag.setText("Required");
            ae++;
        }
        else
        {
            validateemp ve=new validateemp();
            ve.valdage();
        }   
    }//GEN-LAST:event_eagFocusLost

    private void edojFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edojFocusLost
        if(edoj.getText().length()==0)
        {
            lbdoj.setText("Required");
            ae++;
        }        
        else
        {
            validateemp v=new validateemp();
            v.valddate();
        }        
    }//GEN-LAST:event_edojFocusLost

    private void epassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epassFocusLost
        if(epass.getText().length()==0)
        {
            lbpas.setText("Required");
            ae++;
        }        
        else
        {
            validateemp va=new validateemp();
            va.valdpassword();
        }        
    }//GEN-LAST:event_epassFocusLost

    private void eidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eidFocusGained
        lbeid.setText("");
        ae++;
    }//GEN-LAST:event_eidFocusGained

    private void eidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eidFocusLost
        if(eid.getText().length()==0)
        {
            lbeid.setText("Required");
            ae++;
        }
        else
        {
            validateemp ve=new validateemp();
            ve.valdeid();
        }
    }//GEN-LAST:event_eidFocusLost

    private void enameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enameFocusGained
        lbenam.setText("");
        ae++;
    }//GEN-LAST:event_enameFocusGained

    private void enameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enameFocusLost
        if(ename.getText().length()==0)
        {
            lbenam.setText("Required");
            ae++;
        }            
        else
        {
            validateemp ve=new validateemp();
            ve.valdename();
        }
    }//GEN-LAST:event_enameFocusLost

    private void eagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eagFocusGained
        lbag.setText("");
        ae=0;
    }//GEN-LAST:event_eagFocusGained

    private void edojFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edojFocusGained
        lbdoj.setText("");
        ae=0;
    }//GEN-LAST:event_edojFocusGained

    private void epassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epassFocusGained
        lbpas.setText("");
        ae=0;
    }//GEN-LAST:event_epassFocusGained

    private void repassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repassFocusGained
        lbrpass.setText("");
        ae=0;
    }//GEN-LAST:event_repassFocusGained

    private void repassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repassFocusLost
        if(repass.getText().length()==0)
        {
            lbrpass.setText("Required");
            ae++;
        }        
        else
        {
            validateemp ve=new validateemp();
            ve.passmatch();
        }
    }//GEN-LAST:event_repassFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemp;
    private javax.swing.JTextField eag;
    private javax.swing.JButton ebck;
    private javax.swing.JTextField edoj;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    private javax.swing.JPasswordField epass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbag;
    private javax.swing.JLabel lbdoj;
    private javax.swing.JLabel lbeid;
    private javax.swing.JLabel lbenam;
    private javax.swing.JLabel lbpas;
    private javax.swing.JLabel lbrpass;
    private javax.swing.JButton lgot;
    private javax.swing.JPasswordField repass;
    // End of variables declaration//GEN-END:variables
}
