/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minorp;

import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author gaurav
 */
public class AddRoute extends javax.swing.JFrame {

    /**
     * Creates new form AddRoute
     */
    public AddRoute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        src = new javax.swing.JTextField();
        dest = new javax.swing.JTextField();
        dstnc = new javax.swing.JTextField();
        fre = new javax.swing.JTextField();
        adrt = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        lgot = new javax.swing.JButton();
        lbdtnc = new javax.swing.JLabel();
        lbrid = new javax.swing.JLabel();
        lbsrc = new javax.swing.JLabel();
        lbdest = new javax.swing.JLabel();
        lbfre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Route Id");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Source");

        label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 153));
        label.setText("Destination");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Distance");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("Fare");

        rid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ridFocusLost(evt);
            }
        });

        src.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        src.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                srcFocusLost(evt);
            }
        });

        dest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                destFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                destFocusLost(evt);
            }
        });

        dstnc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dstnc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dstncFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dstncFocusLost(evt);
            }
        });

        fre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                freFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                freFocusLost(evt);
            }
        });

        adrt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adrt.setText("Add");
        adrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrtActionPerformed(evt);
            }
        });

        bck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bck.setText("Back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        lgot.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lgot.setText("Logout");
        lgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgotActionPerformed(evt);
            }
        });

        lbdtnc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbdtnc.setForeground(new java.awt.Color(51, 255, 255));

        lbrid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbrid.setForeground(new java.awt.Color(51, 255, 255));

        lbsrc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbsrc.setForeground(new java.awt.Color(51, 255, 255));

        lbdest.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbdest.setForeground(new java.awt.Color(51, 255, 255));

        lbfre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbfre.setForeground(new java.awt.Color(51, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("ADD DRIVER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lgot))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(label)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dstnc)
                            .addComponent(fre, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(rid)
                            .addComponent(src)
                            .addComponent(dest))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdtnc)
                            .addComponent(lbrid)
                            .addComponent(lbsrc)
                            .addComponent(lbdest)
                            .addComponent(lbfre)))
                    .addComponent(bck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(adrt))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgot)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbrid))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsrc))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbdest))
                    .addComponent(label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dstnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbdtnc))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbfre))
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(adrt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bck))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int b;
class validateroute
{
    private void validaterid()
    {
        String a;
        int n;
        n=Integer.parseInt(rid.getText());
        a = rid.getText();
        String pattern = "(\\d{3})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((200<n) && (n<299)))
            {
                lbrid.setText("Invalid");
                b++;
            }
        } 
        else 
        {
            lbrid.setText("Invalid");
            b++;
        }
    }
    private void validatesrc()
    {
        String a;
        int n;
        n=src.getText().length();
        a = src.getText();
        String pattern = "[a-zA-Z\\s]*";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((2<n) && (n<40)))
            {
                lbsrc.setText("Invalid");
                b++;
            }
        } 
        else 
        {
            lbsrc.setText("Invalid");
            b++;
        }
    }
    private void validatedest()
    {
        String a;
        int n;
        n=src.getText().length();
        a = src.getText();
        String pattern = "[a-zA-Z\\s]*";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((2<n) && (n<40)))
            {
                lbdest.setText("Invalid");
                b++;
            }
        } 
        else 
        {
            lbdest.setText("Invalid");
            b++;
        }
    }
    private void validdstnc()
    {
        String a;
        int n;
        n=Integer.parseInt(dstnc.getText());
        a = dstnc.getText();
        String pattern = "(\\d{2,3})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((10<n) && (n<150)))
            {
                lbdtnc.setText("Invalid");
                b++;
            }
        } 
        else 
        {
            lbdtnc.setText("Invalid");
            b++;
        }
    }
    private void validfare()
    {
        String a;
        int n;
        n=Integer.parseInt(fre.getText());
        a = fre.getText();
        String pattern = "(\\d{3,4})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((150<n) && (n<5000)))
            {
                lbfre.setText("Invalid");
                b++;
            }
        } 
        else 
        {
            lbfre.setText("Invalid");
            b++;
        }
    }
}
class add
{
    int rd,dtnc,fr;
    String sorc,dst;
    void adrute()
    {
        String qry;
        rd=Integer.parseInt(rid.getText());
        sorc=src.getText();
        dst=dest.getText();
        dtnc=Integer.parseInt(dstnc.getText());
        fr=Integer.parseInt(fre.getText());
        try
        {
            Connection cn;
            Statement st;
            int rs;
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab","root","GAUsing@2011");
            st=cn.createStatement();
            qry="insert into route(rid,source,dest,distance,fare) values ("+rd+",'"+sorc+"',"
                  + "'"+dst+"',"+dtnc+","+fr+")";
            rs=st.executeUpdate(qry);
            if(rs>0)
            {
                JOptionPane.showMessageDialog(null,"Route added Successfully");
            }
            cn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error : "+ex);
        }
     }
    void clear()
    {
        rid.setText("");
        src.setText("");
        dest.setText("");
        dstnc.setText("");
        fre.setText("");
    }
}
    private void adrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrtActionPerformed
        add ob=new add();
        int dialogbt=JOptionPane.YES_NO_OPTION;
                dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to confirm ?","Confirmation",dialogbt);
                if(dialogbt==JOptionPane.YES_NO_OPTION)
                {
                    if(b!=0)
                        {
                            JOptionPane.showMessageDialog(null,"One or more fields are invalid");
                        }
                        else
                        {
                            ob.adrute();
                            ob.clear();
                        }
                        this.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"New Route Not Added");
                    this.setVisible(true);
                    ob.clear();
                }
    }//GEN-LAST:event_adrtActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        Route rt=new Route();
        rt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bckActionPerformed

    private void lgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgotActionPerformed
        Login lg=new Login();
        int dialogbt=JOptionPane.YES_NO_OPTION;
        dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Confirmation",dialogbt);
        if(dialogbt==JOptionPane.YES_NO_OPTION)
        {
            lg.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.setVisible(true);
        }
    }//GEN-LAST:event_lgotActionPerformed

    private void dstncFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dstncFocusLost
        if(dstnc.getText().length()==0)
        {
            lbdtnc.setText("Required");
            b++;
        }
        else
        {
            validateroute vr=new validateroute();
            vr.validdstnc();
        }
    }//GEN-LAST:event_dstncFocusLost

    private void freFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freFocusLost
        if(fre.getText().length()==0)
        {
            lbfre.setText("Required");
            b++;
        }
        else
        {
            validateroute v=new validateroute();
            v.validfare();
        }
    }//GEN-LAST:event_freFocusLost

    private void ridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ridFocusGained
        lbrid.setText("");
        b=0;
    }//GEN-LAST:event_ridFocusGained

    private void ridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ridFocusLost
        if(rid.getText().length()==0)
        {
            lbrid.setText("Required");
            b++;
        }
        else
        {
            validateroute vr=new validateroute();
            vr.validaterid();
        }
    }//GEN-LAST:event_ridFocusLost

    private void srcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srcFocusGained
        lbsrc.setText("");
        b=0;
    }//GEN-LAST:event_srcFocusGained

    private void srcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srcFocusLost
        if(src.getText().length()==0)
        {
            lbsrc.setText("Required");
            b++;
        }
        else
        {
            validateroute vr=new validateroute();
            vr.validatesrc();
        }
    }//GEN-LAST:event_srcFocusLost

    private void destFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_destFocusGained
        lbdest.setText("");
        b=0;
    }//GEN-LAST:event_destFocusGained

    private void destFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_destFocusLost
        if(dest.getText().length()==0)
        {
            lbdest.setText("Required");
            b++;
        }
        else
        {
            validateroute vr=new validateroute();
            vr.validatedest();
        }
    }//GEN-LAST:event_destFocusLost

    private void dstncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dstncFocusGained
        lbdtnc.setText("");
        b=0;
    }//GEN-LAST:event_dstncFocusGained

    private void freFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freFocusGained
        lbfre.setText("");
        b=0;
    }//GEN-LAST:event_freFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoute().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adrt;
    private javax.swing.JButton bck;
    private javax.swing.JTextField dest;
    private javax.swing.JTextField dstnc;
    private javax.swing.JTextField fre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbdest;
    private javax.swing.JLabel lbdtnc;
    private javax.swing.JLabel lbfre;
    private javax.swing.JLabel lbrid;
    private javax.swing.JLabel lbsrc;
    private javax.swing.JButton lgot;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField src;
    // End of variables declaration//GEN-END:variables
}
