/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minorp;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author gaurav
 */
public class Daytoday extends javax.swing.JFrame {

    /**
     * Creates new form Daytoday
     */
    public Daytoday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ovtm = new javax.swing.JTextField();
        drid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hldy = new javax.swing.JTextField();
        stre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        bck = new javax.swing.JButton();
        lgot = new javax.swing.JButton();
        lbdid = new javax.swing.JLabel();
        lbovtm = new javax.swing.JLabel();
        lbhldy = new javax.swing.JLabel();
        lbdt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Driver Id");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Overtime");

        ovtm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ovtmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ovtmFocusLost(evt);
            }
        });

        drid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dridFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Holiday");

        hldy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hldyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hldyFocusLost(evt);
            }
        });

        stre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        stre.setText("Store");
        stre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Date");

        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });

        bck.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bck.setText("Back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        lgot.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lgot.setText("Logout");
        lgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgotActionPerformed(evt);
            }
        });

        lbdid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbdid.setForeground(new java.awt.Color(51, 255, 255));

        lbovtm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbovtm.setForeground(new java.awt.Color(51, 255, 255));

        lbhldy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbhldy.setForeground(new java.awt.Color(51, 255, 255));

        lbdt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbdt.setForeground(new java.awt.Color(51, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("DAY TO DAY RECORDS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(drid, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(ovtm)
                            .addComponent(hldy)
                            .addComponent(date))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdid)
                            .addComponent(lbovtm)
                            .addComponent(lbhldy)
                            .addComponent(lbdt)))
                    .addComponent(bck))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(97, 97, 97)
                .addComponent(lgot))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(stre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lgot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdid))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ovtm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbovtm))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hldy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbhldy))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdt))
                .addGap(18, 18, 18)
                .addComponent(stre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(bck))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int dd;
class validatepayroll
{
    private void validdrid()
    {
        String a;
        a = drid.getText();
        String pattern = "^dr"+"(\\d{3})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            //System.out.println("Found value: ");
        } 
        else 
        {
            lbdid.setText("Invalid");
            dd++;
        }
    }
    void validatedat()
    {
        int f=1,g=1,yr;
        String a,year,month,day;
        a =date.getText();
        if(a.charAt(4)=='-' && a.charAt(7)=='-')
        {
            year=a.substring(0,4);
            month=a.substring(5,7);
            day=a.substring(8);
            yr=Integer.parseInt(year);
            if (month.equals("04")||month.equals("06")||month.equals("07")||month.equals("09")||
              month.equals("11"))
            {
                g=1;
                String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                Pattern r1 = Pattern.compile(patternd);
                Matcher m1 = r1.matcher(day);
                if (m1.matches( )||day.equals("30"))
                {
                    g=1;
                }
                 else
                {
                    f=0;
                }
          // 30 days
            }
            else if (month.equals("01")||month.equals("03")||month.equals("05")||month.equals("07")
              ||month.equals("08")||month.equals("10")||month.equals("12"))
            {
                g=1;
                String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                Pattern r1 = Pattern.compile(patternd);
                Matcher m1 = r1.matcher(day);
                if (m1.matches( )||day.equals("30")||day.equals("31"))
                {
                    g=1;
                }
                else
                {
                    f=0;
                }
          //31 days
            }
            else if (month.equals("02"))
            {
                g=1;
                int c;
                c=Integer.parseInt(year);
                if ((c%4==0 && c%100==0)||(c%400)==0)
                {
                    String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8|9))$";
                    Pattern r1 = Pattern.compile(patternd);
                    Matcher m1 = r1.matcher(day);
                    if (m1.matches( ))
                    {
                        g=1;
                    }
                    else
                    {
                        f=0;
                    }
                }
                else
                {
                    String patternd = "^((0|1|2)(0|1|2|3|4|5|6|7|8))$";
                    Pattern r1 = Pattern.compile(patternd);
                    Matcher m1 = r1.matcher(day);
                    if (m1.matches( )||day.equals("09")||day.equals("19"))
                    {
                  //  JOptionPane.showMessageDialog(null,"Valid Day");
                    }
                    else
                    {
                        f=0;
                    }
                }
            }
            else
            {
                f=0;
            }
            String patterny = "^((20)\\d{2})$";
            Pattern r = Pattern.compile(patterny);
            Matcher m = r.matcher(year);
            if (m.matches( ))
            {
                if(!(yr<=2020))
                {
                    f=0;
                }
                else
                    g=1;
            }
            else
            {
                f=0;
            }
            if (f==0)
            {
                lbdt.setText("Invalid");
                dd++;
            }
            if (g==1 && f!=0)
            {
           // JOptionPane.showMessageDialog(null,"Valid date");
            }
        }
        else
        {
            lbdt.setText("Invalid");
            dd++;        
        }
    }
    private void validatehldy()
    {
        String a;
        int n,p;
        p=n=Integer.parseInt(ovtm.getText());
        n=Integer.parseInt(hldy.getText());
        a = hldy.getText();
        String pattern = "(\\d{1})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!(n==1 || n==0))
            {
                lbhldy.setText("Invalid");
                dd++;
            }
            if((n==1)&&(p>0))
            {
               JOptionPane.showMessageDialog(null,"Invalid Input for Overtime and Holiday");
               dd++;
            }
        } 
        else 
        {
            
                lbhldy.setText("Invalid");
                dd++;
            
        }
    }
    private void validateovtm()
    {
        String a;
        int n;
        n=Integer.parseInt(ovtm.getText());
        a = ovtm.getText();
        String pattern = "(\\d{1})";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(a);
        if (m.matches( )) 
        {
            if(!((n>0)&&(n<10)))
            {
                lbovtm.setText("Out of Range");
                dd++;
            }
        } 
        else 
        {
            lbovtm.setText("Invalid");
            dd++;
        }
    }
}
class payroll
{
    void add()
    {
        int ot,hld,sal,d,m,y;
        sal=0;
        String qry,dte,did;
        did=drid.getText();
        ot=Integer.parseInt(ovtm.getText());
        hld=Integer.parseInt(hldy.getText());
        dte=date.getText();
        try
            {
                Connection cn;
                Statement st;
                int rs;
                cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab","root","GAUsing@2011");
                st=cn.createStatement();
                qry="insert into salary(did,date,overtime,noofholidays,salary) values('"+did+"',"
                        + "'"+dte+"',"+ot+","+hld+","+sal+")";
                rs=st.executeUpdate(qry);
                if(rs>0)
                {
                    JOptionPane.showMessageDialog(null,"Record saved successfully");
                }
                cn.close();
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Error"+ex);
            }
        
    }
    void clear()
    {
        drid.setText("");
        ovtm.setText("");
        hldy.setText("");
        date.setText("");
    }
}
    private void streActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streActionPerformed
       payroll prl=new payroll();
       if(dd!=0)
           JOptionPane.showMessageDialog(null,"One or more field is invalid");
       else
       {
           prl.add();
           prl.clear();
       }
           this.setVisible(true);      
    }//GEN-LAST:event_streActionPerformed

    private void lgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgotActionPerformed
        Login lg=new Login();
        int dialogbt=JOptionPane.YES_NO_OPTION;
        dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Confirmation",dialogbt);
        if(dialogbt==JOptionPane.YES_NO_OPTION)
        {
            lg.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.setVisible(true);
        }
    }//GEN-LAST:event_lgotActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
       DriverMan dm=new DriverMan();
       dm.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bckActionPerformed

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
       if(date.getText().length()==0)
       {
           lbdt.setText("Required");
           dd++;
       } 
       else
       {
        validatepayroll vp=new validatepayroll();
        vp.validatedat();
       }
    }//GEN-LAST:event_dateFocusLost

    private void ovtmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ovtmFocusLost
       if(ovtm.getText().length()==0)
       {
           lbovtm.setText("Required");
           dd++;
       }   
       else
       {
            validatepayroll v=new validatepayroll();
            v.validateovtm();
       }
        
    }//GEN-LAST:event_ovtmFocusLost

    private void hldyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hldyFocusLost
       if(hldy.getText().length()==0)
       {
           lbhldy.setText("Required");
           dd++;
       }    
       else 
       {
           validatepayroll vpe=new validatepayroll();
            vpe.validatehldy();
       }
        
    }//GEN-LAST:event_hldyFocusLost

    private void dridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dridFocusGained
        lbdid.setText("");
        dd=0;
    }//GEN-LAST:event_dridFocusGained

    private void dridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dridFocusLost
       if(drid.getText().length()==0)
       {
           lbdid.setText("Required");
           dd++;
       }   
       else 
       {
            validatepayroll vp=new validatepayroll();
            vp.validdrid();
       }
        
    }//GEN-LAST:event_dridFocusLost

    private void ovtmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ovtmFocusGained
        lbovtm.setText("");
        dd=0;
    }//GEN-LAST:event_ovtmFocusGained

    private void hldyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hldyFocusGained
        lbhldy.setText("");
        dd=0;
    }//GEN-LAST:event_hldyFocusGained

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        lbdt.setText("");
        dd=0;
    }//GEN-LAST:event_dateFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daytoday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daytoday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daytoday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daytoday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daytoday().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck;
    private javax.swing.JTextField date;
    private javax.swing.JTextField drid;
    private javax.swing.JTextField hldy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbdid;
    private javax.swing.JLabel lbdt;
    private javax.swing.JLabel lbhldy;
    private javax.swing.JLabel lbovtm;
    private javax.swing.JButton lgot;
    private javax.swing.JTextField ovtm;
    private javax.swing.JButton stre;
    // End of variables declaration//GEN-END:variables
}
