/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minorp;

import javax.swing.JOptionPane;

/**
 *
 * @author gaurav
 */
public class Route extends javax.swing.JFrame {

    /**
     * Creates new form Route
     */
    public Route() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adrt = new javax.swing.JButton();
        updtrt = new javax.swing.JButton();
        dltrt = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        vwrt = new javax.swing.JButton();
        lgot = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minorp/images.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 125, 269, 220));

        adrt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        adrt.setText("Add Route");
        adrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrtActionPerformed(evt);
            }
        });
        jPanel1.add(adrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        updtrt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updtrt.setText("Update Route");
        updtrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtrtActionPerformed(evt);
            }
        });
        jPanel1.add(updtrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        dltrt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        dltrt.setText("Delete Route");
        dltrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltrtActionPerformed(evt);
            }
        });
        jPanel1.add(dltrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        bck.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bck.setText("Back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        jPanel1.add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        vwrt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        vwrt.setText("View Route");
        vwrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vwrtActionPerformed(evt);
            }
        });
        jPanel1.add(vwrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 351, -1, -1));

        lgot.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lgot.setText("Logout");
        lgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgotActionPerformed(evt);
            }
        });
        jPanel1.add(lgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("ROUTE MANAGEMENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrtActionPerformed
        AddRoute ar=new AddRoute();
        ar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adrtActionPerformed

    private void updtrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtrtActionPerformed
        UpdateRoute ur=new UpdateRoute();
        ur.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_updtrtActionPerformed

    private void dltrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltrtActionPerformed
        DelRoute dr=new DelRoute();
        dr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dltrtActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        Manager mg=new Manager();
        mg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bckActionPerformed

    private void vwrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vwrtActionPerformed
        ViewRoute vr=new ViewRoute();
        vr.viewroute1("manager");
        vr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vwrtActionPerformed

    private void lgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgotActionPerformed
        Login lg=new Login();
        int dialogbt=JOptionPane.YES_NO_OPTION;
        dialogbt=JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Confirmation",dialogbt);
        if(dialogbt==JOptionPane.YES_NO_OPTION)
        {
            lg.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.setVisible(true);
        }
    }//GEN-LAST:event_lgotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Route().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adrt;
    private javax.swing.JButton bck;
    private javax.swing.JButton dltrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lgot;
    private javax.swing.JButton updtrt;
    private javax.swing.JButton vwrt;
    // End of variables declaration//GEN-END:variables
}
